const jobCategories = [
  { id: 0, name: "Select Job Category" },
  { id: 12, name: "Accountant" },
  { id: 30, name: "Architect / Interior Designer" },
  { id: 1, name: "Back Office / Data Entry" },
  { id: 29, name: "Beautician" },
  { id: 39, name: "Carpenter" },
  { id: 15, name: "Cashier" },
  { id: 19, name: "Content Writer" },
  { id: 31, name: "Cook / Chef" },
  { id: 2, name: "Customer Support / TeleCaller" },
  { id: 28, name: "Delivery" },
  { id: 47, name: "Digital Marketing" },
  { id: 38, name: "Driver" },
  { id: 46, name: "Electrician" },
  { id: 36, name: "Event Management" },
  { id: 43, name: "Fashion Designer" },
  { id: 21, name: "Field Sales" },
  { id: 17, name: "Graphic / Web Designer" },
  { id: 32, name: "Housekeeping" },
  { id: 18, name: "IT / Hardware / Network Engineer" },
  { id: 25, name: "Lab Technician / Pharmacist" },
  { id: 42, name: "Labour/Helper" },
  { id: 37, name: "Legal" },
  { id: 27, name: "Manufacturing" },
  { id: 6, name: "Marketing" },
  { id: 41, name: "Mechanic" },
  { id: 20, name: "Nurse / Compounder" },
  { id: 49, name: "Painter" },
  { id: 50, name: "Peon" },
  { id: 40, name: "Plumber" },
  { id: 13, name: "Receptionist" },
  { id: 16, name: "Recruiter / HR / Admin" },
  { id: 45, name: "Refrigerator & AC Technician" },
  { id: 14, name: "Retail / Counter Sales" },
  { id: 3, name: "Sales / Business Development" },
  { id: 33, name: "Security Guard" },
  { id: 51, name: "Spa" },
  { id: 11, name: "Teacher / Tutor" },
  { id: 44, name: "Technician" },
  { id: 23, name: "Telesales / Telemarketing" },
  { id: 34, name: "Trainer" },
  { id: 48, name: "Video Editor" },
  { id: 35, name: "Waiter / Steward" },
  { id: 24, name: "Ward Boy" },
  { id: 26, name: "Warehouse / Logistics" }
];

export default jobCategories; 