const occupation = [
  "2-wheeler mechanic",
  "2D Animator",
  "2D/3D Architect",
  "2D/3D Designer",
  "2D/3D Interior Designer",
  "3D Animator",
  "3D Graphic Designer",
  "3D Modeling Designer",
  "4-wheeler mechanic",
  "AC Technician",
  "Academic Content Writer",
  "Academic Counsellor",
  "Accountant",
  "Accountant (Articleship)",
  "Accountant (Part -Time)",
  "Accounts & Export Documentation Executive",
  "Accounts Admin",
  "Accounts And Finance Executive",
  "Accounts Assistant",
  "Accounts Associate",
  "Accounts Deputy Manager",
  "Accounts Executive",
  "Accounts Head",
  "Accounts Manager",
  "Accounts Payable Executive",
  "Admin Executive",
  "Admin Supervisor",
  "Administrative Assistant",
  "Admission Counsellor",
  "Advocate",
  "After sales service in-charge",
  "Air Freight Manager",
  "Album Designer",
  "Apparel Sales Retail",
  "Aptitude Trainer",
  "AR Caller",
  "Architect",
  "Area Sales Officer",
  "Aromatherapy Specialist",
  "Art & Craft Teacher",
  "Articleship Accountant",
  "Assistant Architect",
  "Assistant Cook",
  "Assistant HR Manager",
  "Assistant Manager",
  "Assistant Manager Learning & Development",
  "Assistant Manager Training/Training Executive",
  "Assistant Managing Director",
  "Assistant Operations Manager",
  "Assistant Production Manager",
  "Assistant Professor",
  "Assistant Sales Manager",
  "Assistant Store Incharge",
  "Assistant Support Admin",
  "Assistant Teacher",
  "Assistant Telecalling Manager",
  "Associate Advocate",
  "Associate Agency Development Manager",
  "Associate Busiess Development Manager",
  "Associate Financial Analyst",
  "Associate Graphic Designer",
  "Associate Hardware Engineer",
  "Associate Lawyer",
  "Associate Relationship Manager",
  "ATM Cash Loader",
  "Audit / Account Assistant",
  "Audit And Taxation Manager",
  "Audit Assistant",
  "Audit Executive",
  "Audit Manager",
  "Auditor",
  "Auto Driver",
  "AutoCAD Designer",
  "Automobile electric mechanic",
  "Automobile fitter",
  "Automobile Sales Executive",
  "Autopart Sales Associate",
  "Ayurveda Therapist",
  "Back Office Assistant",
  "Back Office Coordinator",
  "Back Office Executive",
  "Back Office Manager",
  "Back Office Operations",
  "Back Office Sales Assistant",
  "Back Office Sales Executive",
  "Back Office Staff",
  "Back Office Staff (Male)",
  "Back Office Team Leader",
  "Backend Executive",
  "Bakery Chef",
  "Banking Assistant",
  "Barista",
  "Beautician",
  "Beauty & Spa Consultant",
  "Beauty Advisor",
  "Beauty Consultant",
  "Beauty Director",
  "Beauty Therapist",
  "Bengali Chef",
  "Bike mechanic",
  "Bike Rider",
  "Billing And TPA Executive",
  "Biology Teacher",
  "Biryani Cook",
  "Blood Collection",
  "Body Massage Therapist",
  "Body Treatment Specialist",
  "Bouncer",
  "Boutique Sales Executive",
  "BPO Manager",
  "BPO Non Voice Process Executive",
  "Bpo Team Leader",
  "BPO Telecaller",
  "BPO Telesales",
  "Branch Relationship Executive",
  "Branch Sales Manager",
  "Branch Sales Officer",
  "Brand Manager",
  "Brand Promoter",
  "Branding Sales Associate",
  "Bread And Donut Chef",
  "Brew Master",
  "Broadband Sales Team Leader",
  "Bulk Kitchen Chef",
  "Bus Driver",
  "Business Administrator",
  "Business Advisor",
  "Business Analyst",
  "Business Developer",
  "Business Development Executive",
  "Business Development Manager",
  "Business Development Officer",
  "Business Initiatives Executive",
  "Business Initiatives Manager",
  "Business Intelligence Manager",
  "Business Manager",
  "Business Operations Manager",
  "Butcher/Kasai",
  "Cab Driver",
  "Cafe Manager",
  "Cafe Staff",
  "Cake Maker",
  "Call Center Executive",
  "Call Centre Agent",
  "Call Centre BPO Executive",
  "Call Centre Executive",
  "Call Quality Analyst",
  "Car mechanic",
  "Car Sales Executive",
  "Car Sales Retail",
  "Career Counsellor",
  "Cargo Freight Executive",
  "Caricature Artist",
  "Carpenter",
  "Carpenter helper",
  "Cashier",
  "Catering Assistant",
  "Center Manager",
  "Chaat Cook",
  "Channel Sales Executive - Software",
  "Channel Sales Executive (Software)",
  "Chartered Accountant",
  "Chartered Accountant (Articleship)",
  "Chartered Financial Analysts",
  "Chef",
  "Chemist",
  "Chemist - Production",
  "Chemist - Quality Control",
  "Chemistry Teacher",
  "Chief Cook",
  "Chinese Cook",
  "Civil draughtsman",
  "Cleaner",
  "Clerk",
  "Client Relationship Manager",
  "Clinic Assistant",
  "Clinic Assistant Veterinary",
  "Clinic Helper",
  "Clinic Treatment Assistant",
  "Clothes Sales Retail",
  "Cluster Control Executive",
  "Cluster Manager",
  "Cluster Sales Officer",
  "CNC Lathe Machine Operator",
  "CNC Machine Operator",
  "Coach",
  "Collection Executive",
  "Collection Manager",
  "College Teacher",
  "Commerce Teacher",
  "Commercial vehicle mechanic",
  "Commercial wireman",
  "Commi 1",
  "Commi 2",
  "Commi 3",
  "Company Driver",
  "Company Secretary",
  "Compliance Executive",
  "Computer Designer (Printing Press)",
  "Computer Hardware Engineer",
  "Computer Operator",
  "Computer Teacher",
  "Construction Electrician",
  "Construction Labour",
  "Construction Sales Executive",
  "Consumer Durable Loan Sales Executive",
  "Content Analyst",
  "Content Developer",
  "Content Editor",
  "Content Manager",
  "Content Marketing",
  "Content Quality Analyst",
  "Content Specialist",
  "Content Writer",
  "Content Writer & Editor",
  "Continental Cook",
  "Cook",
  "Copywriter",
  "Corel Draw Designer",
  "Corporate Lawyer",
  "Corporate Product Sales",
  "Corporate Sales Executive",
  "Corporate Tie Ups",
  "Corporate Trainer",
  "Cost Accountant",
  "Counsellor",
  "Counter Billing Executive",
  "Counter Sales",
  "Counter Sales Executive",
  "Counter Sales Guy",
  "Counter Salesman",
  "Courier Delivery",
  "Creative Designer",
  "Creative Manager",
  "Credit Analyst",
  "Credit Card Sales",
  "Credit Controller",
  "Credit Officer",
  "CSR Manager",
  "Customer Care Executive",
  "Customer Care Manager",
  "Customer Care Officer",
  "Customer Care Representative",
  "Customer Care Service",
  "Customer Relationship Associate",
  "Customer Relationship Executive",
  "Customer Relationship Manager",
  "Customer Sales Executive",
  "Customer Support Executive",
  "Customer Support Team Leader",
  "Customer Verification Executive",
  "Dance Teacher",
  "Dance Trainer",
  "Data Entry Executive",
  "Data Entry Operator",
  "Data Operator",
  "Data Processing Officer",
  "Data Processor",
  "Delivery Boy",
  "Delivery Executive",
  "Delivery Head",
  "Delivery Manager",
  "Dental Assistant",
  "Dental Assistant/Receptionist",
  "Dental Chairside Assistant",
  "Denting/Painting mechanic",
  "Desktop Support Engineer",
  "Digital Marketing Assistant",
  "Digital Marketing Executive",
  "Digital marketing manager",
  "Diploma/Degree Architect",
  "Dish Washer",
  "Dispatch Executive",
  "Dispatcher",
  "Distribution Executive",
  "Document Scanning",
  "Document Scanning (Office)",
  "Document Verification (Office)",
  "Documentation Executive",
  "Draftsman Architect",
  "Draughtsman Architect",
  "Driver",
  "DTH Technician",
  "DTP Computer Operator",
  "DTP Designer",
  "DTP Executive",
  "DTP Operator",
  "DTP Promoter",
  "E commerce marketing executive",
  "E-commerce Marketing Executive",
  "Ecommerce Account Manager",
  "Ecommerce Operations Executive",
  "Ecommerce Sales Executive",
  "Economics Teacher",
  "Editorial Assistant",
  "Education Counsellor",
  "Electrical car mechanic",
  "Electrician",
  "Electronic Data Processing",
  "Electronics Sales Retail",
  "Electronics Technician",
  "Email & Chat Process Executive",
  "Email & Chat Support Executive",
  "Email And Chat Process Executive",
  "Email Chat Support Executive",
  "Email Process Executive",
  "Engine mechanic",
  "English Teacher",
  "English Writer",
  "Event Assistant",
  "Event Coordinator",
  "Event Designer",
  "Event Manager",
  "Event Organizer",
  "Event Promoter",
  "Executive Assistant",
  "Executive Secretary",
  "Export Coordinator",
  "Exterior Surface Painter",
  "Eye Wear Sales Retail",
  "Fabrication Labour",
  "Fabrication mechanic",
  "Factory Helper",
  "Factory Helper (Male)",
  "Factory Labour",
  "Factory Supervisor",
  "Factory Worker",
  "Fashion Consultant",
  "Fashion Design Faculty",
  "Fashion designer",
  "Fashion Merchandiser",
  "Fast Food Cook",
  "Fast Food Helper",
  "Field Boy",
  "Field Collection Executive",
  "Field Coordinator",
  "Field Executive",
  "Field Sales Coordinator",
  "Field Sales Executive",
  "Field Sales Manager",
  "Field Sales Officer",
  "Field Sales Representative",
  "Field Sales Specialist",
  "Field Supervisor",
  "Field Support Engineer",
  "Field Verification Executive",
  "Finance / Accounts",
  "Finance Executive",
  "Financial Accountant",
  "Financial Service Sales Associate",
  "Fire Alarm Technician",
  "Fire Officer",
  "Fitness Trainer",
  "Fitter",
  "Fleet Manager",
  "Floor Incharge",
  "Floor Manager",
  "Floor Painter",
  "FMCG Field Sales Executive",
  "FMCG Sales",
  "FMCG Sales Team Leader",
  "Food and Beverage Manager",
  "Food Chain Sales Retail",
  "Food Delivery",
  "Footwear Sales Retail",
  "Frame maker",
  "Franchise Manager",
  "Freight Broker",
  "Freight Broker- Customer Support",
  "Freight Driver",
  "Freight Executive",
  "Freight Forwarder",
  "Freight Forwarder - Marketing",
  "Freight Forwarding Executive",
  "Freight Manager",
  "Front Desk Executive",
  "Front Desk Receptionist",
  "Front Office Manager",
  "Front Office Receptionist",
  "Front Office/Sales Executive",
  "Fulfillment Centre Supervisor",
  "Furniture carpenter",
  "Furniture Designer",
  "Furniture factory supervisor",
  "Furniture fitter",
  "Furniture Salesman",
  "Gardener",
  "Garment Graphic Designer",
  "Garment Salesman",
  "General mechanic",
  "General Technician",
  "GI/Hose pipe plumber",
  "GPS Tracker",
  "Graphic Design Trainer",
  "Graphic Designer",
  "Graphic Illustrator",
  "Ground Coordinator",
  "Gym Trainer",
  "Hair Cutting Executive",
  "Hairdresser",
  "Hardware Engineer",
  "Head Cook",
  "Head Master",
  "Head Mistress",
  "Healthcare Assistant",
  "Heavy Driver",
  "Heavy Machine Operator",
  "Helpdesk Executive (Office)",
  "Helper",
  "Helper / Delivery",
  "High tension wireman",
  "Hindi Content Writer",
  "Hindi Content Writter",
  "Hindi Teacher",
  "Hindi Telecaller",
  "Hobby Teacher",
  "Holiday Consultant",
  "Home Appliances Sales Retail",
  "Home Appliances Technician",
  "Home Care Nursing",
  "Home Collection Coordinator",
  "Hospital Assistant",
  "Hospital Ward Boy",
  "Hotel Cleaner",
  "Hotel Receptionist",
  "Hotel Sales Manager",
  "House cleaner",
  "House Keeping Staff",
  "House Watchman",
  "Household wireman",
  "Housekeeping Associate",
  "Housekeeping Attendant",
  "Housekeeping Executive",
  "Housekeeping Helper",
  "Housekeeping Manager",
  "Housekeeping Officer",
  "Housekeeping Room Attendant",
  "Housekeeping Supervisor",
  "Housekeeping Team Leader",
  "HR Analyst",
  "HR Assistant",
  "HR Executive",
  "HR Head",
  "HR Manager",
  "HR Officer",
  "HR Operation Executive",
  "HR Operations",
  "HR Recruiter",
  "Hr/Admin",
  "Hub Incharge",
  "Hub Supervisor",
  "Human Resource Executive",
  "Human Resource Generalist",
  "HVAC Technician",
  "Hydrotherapy Technician",
  "IELTS Teacher",
  "Immigration Consultant",
  "Import Export Executive",
  "Import Export Freight Forwarding Executive",
  "Import Freight Forwarding Executive",
  "In House Advocate",
  "In Shop Sales Staff",
  "Indian And Tandoor Cook",
  "Indian Cook",
  "Indoor Sales Executive",
  "Industrial Painter",
  "Inside Sales Executive",
  "Insurance Advisor",
  "Insurance Sales",
  "Interior Designer",
  "Interior Draftsman",
  "Interior Showroom Sales Executive",
  "Interior Site Supervisor",
  "Interior Surface Painter",
  "International BPO Executive",
  "International Call Center",
  "International Customer Representative",
  "International Customer Support Executive",
  "International Lead Generation Executive",
  "International Non Voice Process",
  "International Outbound Voice Executive",
  "International Sales Executive",
  "International Telesales Executive",
  "International Travel Consultant",
  "International Voice Care Agent",
  "International Voice Process",
  "International Voice Process Agent",
  "Inventory Executive",
  "Inventory Manager",
  "Investment Counsellor",
  "IT Hardware Engineer",
  "IT Professional",
  "IT Sales Executive",
  "IT Technician/Network Technician",
  "Item Delivery",
  "ITI Electrician",
  "ITI Technician",
  "Janitor",
  "Jewellery Salesman",
  "Junior Accountant",
  "Junior Advocate",
  "Junior Architect",
  "Junior Beautician",
  "Junior Chemist",
  "Junior Clerk",
  "Junior DTP Operator",
  "Junior Lawyer",
  "Junior Machine Operator",
  "Junior Trainer",
  "Kannada Teacher",
  "Key Account Executive",
  "Key Account Manager",
  "Key Relationship Manager",
  "Key Sales Manager",
  "Kitchen carpenter",
  "Kitchen Helper",
  "Kitchen Staff",
  "KYC Field Executive",
  "Lab Assistant",
  "Lab Chemist",
  "Lab Technician",
  "Labour",
  "Labour Supervisor",
  "Language Teacher",
  "Laser Hair Removal Technician",
  "Lastmile Operation Executive",
  "Lathe Machine Operator",
  "Law Officer",
  "Lawyer",
  "Lead Generation Executive",
  "Legal Advisor",
  "Legal Assistant",
  "Legal Associate",
  "Legal Consultant",
  "Legal Executive",
  "Legal Head",
  "Legal Manager",
  "Legal Officer",
  "Librarian",
  "Library Assistant",
  "Lift/Elevator Technician",
  "Light Driver",
  "Light Machine Operator",
  "Line Man",
  "LMV Mechanic",
  "Loader",
  "Loader/Unloader",
  "Loan Sales",
  "Logistics Freight Forwarder",
  "Logistics Manager",
  "Logistics Supervisor",
  "Logo Designer",
  "Low tension wireman",
  "Lower Division Clerk (LDC)",
  "Machine Maintenance Officer",
  "Machine Maintenance Supervisor",
  "Machine Operator",
  "Machine Supervisor",
  "Machinery Painter",
  "Machinist",
  "Maid",
  "Maintenance Technician",
  "Mall Manager",
  "Mall Sales Executive",
  "Manufacturing Site Supervisor",
  "Marathi Teacher",
  "Marketing Executive",
  "Marketing Field Executive",
  "Marketing Head",
  "Marketing Manager",
  "Marketing Representative",
  "Massage Therapist Specialist",
  "Maths Teacher",
  "Mechanic motor vehicle",
  "Mechanical draughtsman",
  "Media Sales Executive",
  "Medical Content Writer",
  "Medical Lab Technician",
  "Medical Representative",
  "Medical Sales",
  "Medical Staff",
  "Medical Writer",
  "Milk Delivery",
  "MIS Executive",
  "Mobile Hardware Engineer",
  "Mobile Salesman",
  "Modular carpenter",
  "Modular Kitchen Designer",
  "Motion Designer",
  "Motion Graphic Designer",
  "Mughlai Cook",
  "Multi-Skilled Technician ( MST)",
  "Multiproduct Technician",
  "Music Teacher",
  "Mutual Fund Sales",
  "Nail Art Technician",
  "Network Engineer",
  "Network Marketing",
  "News Writter",
  "North Indian Cook",
  "Nursery Teacher",
  "Nursing Superintendent",
  "Nursing Supervisor",
  "Office Admin",
  "Office Assistant",
  "Office Boy",
  "Office Boy (Part Time)",
  "Office Compounder",
  "Office Coordinator",
  "Office Executive",
  "Office Staff",
  "Ola / Uber Driver",
  "Online Advertising",
  "Online Brand Promoting",
  "Online Community Manager",
  "Online Marketing Executive",
  "Online Marketing Strategist",
  "Online Media",
  "Online Retail",
  "Online Sales Executive",
  "Operation Executive",
  "Operation Manager",
  "Operations Assistant",
  "Operations Associate",
  "Outbound Sales Executive",
  "Outside Sales Executive",
  "Packaging Boy",
  "Packing Staff",
  "Painter",
  "Pantry boy",
  "Para Legal",
  "Pastry Cook",
  "Pathology Lab Technician",
  "Patient Care",
  "Payroll Executive",
  "Personal Assistant",
  "Personal Driver",
  "Personal Secretary",
  "Petrol Pump Manager",
  "Pharmaceutical Chemist",
  "Pharmacist",
  "Pharmacist Assistant",
  "Pharmacist Helper",
  "Pharmacy Counter Salesman",
  "Phlebotomist",
  "Phlebotomist - Home Collection",
  "Photo Editor",
  "Photographer",
  "Photoshop Designer",
  "Photoshop specialist",
  "Physical Education Teacher",
  "Physics Teacher",
  "Picker",
  "Picker / Loader",
  "Picker / Packer",
  "Pickup Boy",
  "Pipeline Labourer",
  "Pipeline plumber",
  "Pizza Maker",
  "Plumber",
  "Plumber fitter",
  "Plumber general",
  "Plumber maintenance",
  "Pre-Primary Teacher",
  "Pre-Sales Executive",
  "Preschool Teacher",
  "Pricing Executive -Freight Forwarding",
  "Primary Teacher",
  "Private Assistant",
  "Private Company Driver",
  "Private Secretary",
  "Product Marketing",
  "Production Manager",
  "Professor",
  "Project Sales Executive",
  "Promoter",
  "Promotion Sales",
  "Proof Reader",
  "Property Manager",
  "Property Sales Executive",
  "Property Supervisor",
  "PT Teacher",
  "Public Prosecutor",
  "Pumps-dual system plumber",
  "Purchase Executive",
  "Purchase Manager",
  "QC Chemist",
  "Quality Analyst",
  "Quality Assurance Executive",
  "Quality Auditor",
  "Quality Consultant",
  "Quality Control Engineer",
  "Quality Control Manager",
  "Quality Inspector",
  "Quality Manager",
  "Quality Verifiers",
  "Quantity Surveyor",
  "RAC Technician",
  "Real Estate Sales",
  "Real Estate Telesales Executive",
  "Receptionist",
  "Receptionist Executive",
  "Receptionist/Sales Executive",
  "Recruiter",
  "Recruitment Associate",
  "Reflexology Specialist",
  "Refrigerator Technician",
  "Regioanl Language Sales",
  "Registerd Pharmacist",
  "Relationship Manager",
  "Relationship Officer",
  "Repair carpenter",
  "Repair Technician",
  "Restaurant Captain",
  "Restaurant Manager",
  "Restaurant Waiter",
  "Retail Executive",
  "Retail Executives",
  "Retail Pharmacist",
  "Retail Sales Executive",
  "Retail Sales Manager",
  "Retail Sales Officer",
  "Retailer",
  "Retention Executive",
  "Rice Salesman",
  "RO Water Filter Technician",
  "Sales & Freight Forwarding Manager",
  "Sales & Marketing Executive",
  "Sales Co-ordinator",
  "Sales Coordinator / Executive",
  "Sales Executive",
  "Sales Manager",
  "Sales Recruiter",
  "Sales Representative",
  "Sales Staff (In Shop)",
  "Sales Telecaller",
  "Salon Receptionist",
  "Salon Worker",
  "Saree Salesman",
  "School Counsellor",
  "School Teacher",
  "Science Teacher",
  "Sea Freight Manager",
  "Secondary Teacher",
  "Secretary",
  "Security Guard",
  "Security Guard (Night Shift)",
  "Security Guard (Part Time)",
  "Security Guard Supervisor",
  "Security Officer",
  "Security Personnel",
  "Security Staff",
  "Security Supervisor",
  "Seller Support Executive",
  "Semi Non Voice Process Executive",
  "Senior Accountant",
  "Senior Architect",
  "Senior Beautician",
  "Senior Chemist",
  "Senior Clerk",
  "Senior Content Developer",
  "Senior Content Editor",
  "Senior Content Manager",
  "Senior Content Writer",
  "Senior Cook",
  "Senior Counsellor",
  "Senior Delivery Manager",
  "Senior DTP Operator",
  "Senior Field Sales Executive",
  "Senior Field Sales Manager",
  "Senior Field Sales Officer",
  "Senior Field Sales Representative",
  "Senior Graphic Designer",
  "Senior HR Executive",
  "Senior Lab Technician",
  "Senior Machine Operator",
  "Senior Subject Matter Expert",
  "Senior Tax Consultant",
  "Senior Telecaller",
  "Senior Telesales Executive",
  "Senior Trainer",
  "SEO Executive",
  "Service advisor",
  "Service engineer",
  "Shipping Freight Assistant Manager",
  "Shop Assistant",
  "Shop Keeper",
  "Shop Manager",
  "Shop Salesman",
  "Shop Staff",
  "Showroom Sales",
  "Showroom Sales Executive",
  "SIM Card Sales",
  "Skin Cosmetic Treatment Assistant",
  "Social Media Content Writer",
  "Social media expert",
  "Social Media Manager",
  "Social Media Marketing",
  "Social Media marketing executive",
  "Sofa carpenter",
  "Soft Skills Trainer",
  "Sorting Associate",
  "South Indian Cook",
  "Spa Attendant",
  "Spa Coordinator",
  "Spa Manager",
  "Spa Receptionist",
  "Spa Therapist",
  "Spa Trainer",
  "Sports Salesman",
  "Sports Teacher",
  "SST Teacher",
  "Staff Nurse",
  "Station Associate",
  "Stencil Painter",
  "Stenographer",
  "Steward",
  "Stock Manager",
  "Store Assistant",
  "Store Associate",
  "Store Executive",
  "Store Helper",
  "Store Incharge",
  "Store Keeper",
  "Store Manager",
  "Store Officer",
  "Store Sales Executive",
  "Store Supervisor",
  "Stylist",
  "Supervisor",
  "Surface Painter",
  "Survey Clerk",
  "Sweeper",
  "Sweet Salesman",
  "System Admin",
  "Talent Manager",
  "Tally Executive",
  "Tally Operater",
  "Tally Operator",
  "Tally Support Executive",
  "Tax Assistant",
  "Tax Consultant",
  "Taxation Accountant",
  "Teacher",
  "Technical Assistant",
  "Technical Content Writer",
  "Technical Recruiter",
  "Technical Sales Executive",
  "Technical Supervisor",
  "Technical Writer",
  "Technician",
  "Technician Helper",
  "Technician Mechatronics",
  "Tele calling",
  "Telecaller",
  "Telecaller Inbound",
  "Telecaller Outbound",
  "Telecalling Assistant",
  "Telecalling Executive",
  "Telecalling Manager",
  "Telecalling Supervisor",
  "Telecalling Team Leader",
  "TeleMarketing",
  "Telephone Operator",
  "Telesales",
  "Tempo Driver",
  "Textile Salesman",
  "Texture Painter",
  "Tool and Die Maker",
  "Tour Package Sales Executive",
  "Trainer",
  "Transport Coordinator",
  "Transport Manager",
  "Transport Supervisor",
  "Travel Consultant",
  "Travel Counsellor",
  "Travel Sales Executive",
  "Truck Driver",
  "Tuition teacher",
  "Turner",
  "Tutor",
  "TV Technician",
  "UI / UX Designer",
  "UI/UX Designer",
  "Unisex Hairdresser",
  "Vehicle Driver",
  "Vendor Management",
  "Verification Executive",
  "Vet Assistant",
  "Video Editor",
  "Videographer",
  "Virtual Assistant",
  "Visual Effects (VFX) Designer",
  "Voice & Accent Trainer",
  "Voice & Non-Voice Call Center Agent",
  "Voice Process Agent",
  "Voice Process Executive",
  "Waiter",
  "Ward Boy",
  "Ward Secretary",
  "Warehouse Assistant",
  "Warehouse Executive",
  "Warehouse Incharge",
  "Warehouse Manager",
  "Warehouse Supervisor",
  "Washing Machine Technician",
  "Watchman",
  "Web & Graphic Designer",
  "Web Designer",
  "Wedding Album Designer",
  "Wedding Assistant",
  "Welder",
  "Wellness Therapist",
  "Wheel service mechanic",
  "Wholesale Salesman",
  "Wooden polisher",
  "Woodworks mechanic",
  "Worker general",
  "X-Ray Technician",
  "Yoga Trainer"
];

export default occupation;